server:
  maxThreads: 512
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

jerseyClient:
  gzipEnabled: false
  gzipEnabledForRequests: false
  chunkedEncodingEnabled: false
  timeout: 30000ms

logging:
  level: INFO
  loggers:
    com.demo: DEBUG

mongodbUri: ${MONGODB_URI}

swagger:
  basePath: /customer-biller-service
  resourcePackage: com.blocities.customerbiller.api
  scan: true
  info:
    version: "1.0.0"
    title: "Starter App"
    description: ""
    termsOfService: "http://swagger.io/terms/"
    contact:
      name: "Starter App"
    license:
      name: ""